/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package es.upm.oeg.librairy.service.modeler.facade.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Similarity { 
  CONCURRENCE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Similarity\",\"namespace\":\"es.upm.oeg.librairy.service.modeler.facade.model\",\"symbols\":[\"CONCURRENCE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
