/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.librairy.service.modeler.facade.model;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface ModelerService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"ModelerService\",\"namespace\":\"org.librairy.service.modeler.facade.model\",\"types\":[{\"type\":\"record\",\"name\":\"Word\",\"fields\":[{\"name\":\"value\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"},{\"name\":\"score\",\"type\":\"double\",\"default\":0.0}]},{\"type\":\"record\",\"name\":\"Topic\",\"fields\":[{\"name\":\"id\",\"type\":\"int\",\"default\":-1},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"},{\"name\":\"description\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"}]}],\"messages\":{\"inference\":{\"request\":[{\"name\":\"text\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}],\"response\":{\"type\":\"array\",\"items\":\"double\"}},\"topics\":{\"request\":[],\"response\":{\"type\":\"array\",\"items\":\"Topic\"}},\"words\":{\"request\":[{\"name\":\"topicId\",\"type\":\"int\"},{\"name\":\"maxWords\",\"type\":\"int\"}],\"response\":{\"type\":\"array\",\"items\":\"Word\"}}}}");
  java.util.List<java.lang.Double> inference(java.lang.String text) throws org.apache.avro.AvroRemoteException;
  java.util.List<org.librairy.service.modeler.facade.model.Topic> topics() throws org.apache.avro.AvroRemoteException;
  java.util.List<org.librairy.service.modeler.facade.model.Word> words(int topicId, int maxWords) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends ModelerService {
    public static final org.apache.avro.Protocol PROTOCOL = org.librairy.service.modeler.facade.model.ModelerService.PROTOCOL;
    void inference(java.lang.String text, org.apache.avro.ipc.Callback<java.util.List<java.lang.Double>> callback) throws java.io.IOException;
    void topics(org.apache.avro.ipc.Callback<java.util.List<org.librairy.service.modeler.facade.model.Topic>> callback) throws java.io.IOException;
    void words(int topicId, int maxWords, org.apache.avro.ipc.Callback<java.util.List<org.librairy.service.modeler.facade.model.Word>> callback) throws java.io.IOException;
  }
}