/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.librairy.service.modeler.facade.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Topic extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Topic\",\"namespace\":\"org.librairy.service.modeler.facade.model\",\"fields\":[{\"name\":\"id\",\"type\":\"int\",\"default\":-1},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"},{\"name\":\"description\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"},{\"name\":\"entropy\",\"type\":\"double\",\"default\":0.0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private int id;
   private java.lang.String name;
   private java.lang.String description;
   private double entropy;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Topic() {}

  /**
   * All-args constructor.
   */
  public Topic(java.lang.Integer id, java.lang.String name, java.lang.String description, java.lang.Double entropy) {
    this.id = id;
    this.name = name;
    this.description = description;
    this.entropy = entropy;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return description;
    case 3: return entropy;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: name = (java.lang.String)value$; break;
    case 2: description = (java.lang.String)value$; break;
    case 3: entropy = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'description' field.
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.String value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'entropy' field.
   */
  public java.lang.Double getEntropy() {
    return entropy;
  }

  /**
   * Sets the value of the 'entropy' field.
   * @param value the value to set.
   */
  public void setEntropy(java.lang.Double value) {
    this.entropy = value;
  }

  /** Creates a new Topic RecordBuilder */
  public static org.librairy.service.modeler.facade.model.Topic.Builder newBuilder() {
    return new org.librairy.service.modeler.facade.model.Topic.Builder();
  }
  
  /** Creates a new Topic RecordBuilder by copying an existing Builder */
  public static org.librairy.service.modeler.facade.model.Topic.Builder newBuilder(org.librairy.service.modeler.facade.model.Topic.Builder other) {
    return new org.librairy.service.modeler.facade.model.Topic.Builder(other);
  }
  
  /** Creates a new Topic RecordBuilder by copying an existing Topic instance */
  public static org.librairy.service.modeler.facade.model.Topic.Builder newBuilder(org.librairy.service.modeler.facade.model.Topic other) {
    return new org.librairy.service.modeler.facade.model.Topic.Builder(other);
  }
  
  /**
   * RecordBuilder for Topic instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Topic>
    implements org.apache.avro.data.RecordBuilder<Topic> {

    private int id;
    private java.lang.String name;
    private java.lang.String description;
    private double entropy;

    /** Creates a new Builder */
    private Builder() {
      super(org.librairy.service.modeler.facade.model.Topic.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.librairy.service.modeler.facade.model.Topic.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.entropy)) {
        this.entropy = data().deepCopy(fields()[3].schema(), other.entropy);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Topic instance */
    private Builder(org.librairy.service.modeler.facade.model.Topic other) {
            super(org.librairy.service.modeler.facade.model.Topic.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.entropy)) {
        this.entropy = data().deepCopy(fields()[3].schema(), other.entropy);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public org.librairy.service.modeler.facade.model.Topic.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public org.librairy.service.modeler.facade.model.Topic.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'name' field */
    public java.lang.String getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public org.librairy.service.modeler.facade.model.Topic.Builder setName(java.lang.String value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'name' field */
    public org.librairy.service.modeler.facade.model.Topic.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'description' field */
    public java.lang.String getDescription() {
      return description;
    }
    
    /** Sets the value of the 'description' field */
    public org.librairy.service.modeler.facade.model.Topic.Builder setDescription(java.lang.String value) {
      validate(fields()[2], value);
      this.description = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'description' field has been set */
    public boolean hasDescription() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'description' field */
    public org.librairy.service.modeler.facade.model.Topic.Builder clearDescription() {
      description = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'entropy' field */
    public java.lang.Double getEntropy() {
      return entropy;
    }
    
    /** Sets the value of the 'entropy' field */
    public org.librairy.service.modeler.facade.model.Topic.Builder setEntropy(double value) {
      validate(fields()[3], value);
      this.entropy = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'entropy' field has been set */
    public boolean hasEntropy() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'entropy' field */
    public org.librairy.service.modeler.facade.model.Topic.Builder clearEntropy() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public Topic build() {
      try {
        Topic record = new Topic();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.String) defaultValue(fields()[1]);
        record.description = fieldSetFlags()[2] ? this.description : (java.lang.String) defaultValue(fields()[2]);
        record.entropy = fieldSetFlags()[3] ? this.entropy : (java.lang.Double) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
