/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.librairy.service.modeler.facade.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TopicDistribution extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TopicDistribution\",\"namespace\":\"org.librairy.service.modeler.facade.model\",\"fields\":[{\"name\":\"topic\",\"type\":{\"type\":\"record\",\"name\":\"Topic\",\"fields\":[{\"name\":\"id\",\"type\":\"int\",\"default\":-1},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"},{\"name\":\"description\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"}]}},{\"name\":\"score\",\"type\":\"double\",\"default\":0.0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private org.librairy.service.modeler.facade.model.Topic topic;
   private double score;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public TopicDistribution() {}

  /**
   * All-args constructor.
   */
  public TopicDistribution(org.librairy.service.modeler.facade.model.Topic topic, java.lang.Double score) {
    this.topic = topic;
    this.score = score;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return topic;
    case 1: return score;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: topic = (org.librairy.service.modeler.facade.model.Topic)value$; break;
    case 1: score = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'topic' field.
   */
  public org.librairy.service.modeler.facade.model.Topic getTopic() {
    return topic;
  }

  /**
   * Sets the value of the 'topic' field.
   * @param value the value to set.
   */
  public void setTopic(org.librairy.service.modeler.facade.model.Topic value) {
    this.topic = value;
  }

  /**
   * Gets the value of the 'score' field.
   */
  public java.lang.Double getScore() {
    return score;
  }

  /**
   * Sets the value of the 'score' field.
   * @param value the value to set.
   */
  public void setScore(java.lang.Double value) {
    this.score = value;
  }

  /** Creates a new TopicDistribution RecordBuilder */
  public static org.librairy.service.modeler.facade.model.TopicDistribution.Builder newBuilder() {
    return new org.librairy.service.modeler.facade.model.TopicDistribution.Builder();
  }
  
  /** Creates a new TopicDistribution RecordBuilder by copying an existing Builder */
  public static org.librairy.service.modeler.facade.model.TopicDistribution.Builder newBuilder(org.librairy.service.modeler.facade.model.TopicDistribution.Builder other) {
    return new org.librairy.service.modeler.facade.model.TopicDistribution.Builder(other);
  }
  
  /** Creates a new TopicDistribution RecordBuilder by copying an existing TopicDistribution instance */
  public static org.librairy.service.modeler.facade.model.TopicDistribution.Builder newBuilder(org.librairy.service.modeler.facade.model.TopicDistribution other) {
    return new org.librairy.service.modeler.facade.model.TopicDistribution.Builder(other);
  }
  
  /**
   * RecordBuilder for TopicDistribution instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TopicDistribution>
    implements org.apache.avro.data.RecordBuilder<TopicDistribution> {

    private org.librairy.service.modeler.facade.model.Topic topic;
    private double score;

    /** Creates a new Builder */
    private Builder() {
      super(org.librairy.service.modeler.facade.model.TopicDistribution.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.librairy.service.modeler.facade.model.TopicDistribution.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.topic)) {
        this.topic = data().deepCopy(fields()[0].schema(), other.topic);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.score)) {
        this.score = data().deepCopy(fields()[1].schema(), other.score);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing TopicDistribution instance */
    private Builder(org.librairy.service.modeler.facade.model.TopicDistribution other) {
            super(org.librairy.service.modeler.facade.model.TopicDistribution.SCHEMA$);
      if (isValidValue(fields()[0], other.topic)) {
        this.topic = data().deepCopy(fields()[0].schema(), other.topic);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.score)) {
        this.score = data().deepCopy(fields()[1].schema(), other.score);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'topic' field */
    public org.librairy.service.modeler.facade.model.Topic getTopic() {
      return topic;
    }
    
    /** Sets the value of the 'topic' field */
    public org.librairy.service.modeler.facade.model.TopicDistribution.Builder setTopic(org.librairy.service.modeler.facade.model.Topic value) {
      validate(fields()[0], value);
      this.topic = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'topic' field has been set */
    public boolean hasTopic() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'topic' field */
    public org.librairy.service.modeler.facade.model.TopicDistribution.Builder clearTopic() {
      topic = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'score' field */
    public java.lang.Double getScore() {
      return score;
    }
    
    /** Sets the value of the 'score' field */
    public org.librairy.service.modeler.facade.model.TopicDistribution.Builder setScore(double value) {
      validate(fields()[1], value);
      this.score = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'score' field has been set */
    public boolean hasScore() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'score' field */
    public org.librairy.service.modeler.facade.model.TopicDistribution.Builder clearScore() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public TopicDistribution build() {
      try {
        TopicDistribution record = new TopicDistribution();
        record.topic = fieldSetFlags()[0] ? this.topic : (org.librairy.service.modeler.facade.model.Topic) defaultValue(fields()[0]);
        record.score = fieldSetFlags()[1] ? this.score : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
